name: build

on:
  push:
    branches:
    - main
    - release**
    paths-ignore:
      - '**.md'
      - '**.rst'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.rst'

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: False
      matrix:
        #os: [windows, ubuntu, macos]
        # TODO need to figure out how to install libspatialindex-dev for
        # windows and macos
        os: [ubuntu]
        python-version: ["3.8"]


    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v4
      with:
        path: ~/.cache/pip

    - name: Install dependencies
      run: |
        sudo apt-get install libspatialindex-dev
        pip install .
        pip install pytest pytest-cov

    - run: pip install flake8
    - name: Lint with flake8
      # TODO use .flake8 from projectmesa/mesa
      run: flake8 . --ignore=E501 --select=B,C,E,F,W,T4,B9 --exclude=docs,build

    - name: Test with pytest
      run: pytest --cov=mesa_geo tests/ --cov-report=xml
    - if: matrix.os == 'ubuntu'
      name: Codecov
      uses: codecov/codecov-action@v2