name: CI

on:
  push:
    branches:
      - main
      - 'v[0-9]*'
    tags:
      - 'v[0-9]*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.8"]
        django_version: ["32", "42", "50"]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Choose Python version ${{ matrix.python_version }}
        uses: actions/setup-python@v6
        with:
          python-version: '${{ matrix.python_version }}'
          cache: 'pip'
      - name: install tox (with uv)
        run: python3 -m pip install tox tox-uv
      - name: run tox
        run: tox -e 'py${{ matrix.python_version }}-django${{ matrix.django_version }}'