name: run-tests
on:
  pull_request:
    branches:
      - main
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    name: Check CloudFormation syntax with cfn-lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - run: pip install --requirement $GITHUB_WORKSPACE/requirements.txt
      - run: make cfn-lint
